services:

  app:
    build: .
    ports:
      - 3000:3000
      #- 3001:3001
    volumes:
      - .:/home/node/app
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/partner1
    command: sh -c "./wait-for-it.sh db:3306 -- npm run migrate:partner1 && npm run start:dev"
    depends_on:
      - db

  db:
    image: mysql:8.0.30-debian
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: partner1
    ports:
      - 3306:3306
    #volumes:
    #  - ./.docker/mysql:/docker-entrypoint-initdb.d
    #   - ./.docker/dbdata:/var/lib/mysql